name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change this to match your preferred Python version
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx==6.2.1 sphinx_rtd_theme==1.2.2
      - name: Sphinx build
        run: |
          sphinx-apidoc -o docs refineryframe
          cd docs
          make html
          ls -la _build/html/
          mkdir build
          mv _build/* build/.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/test' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true
