name: docs_pages_workflow

# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ test ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          # python -m pip install sphinxcontrib-apidoc
          python -m pip install sphinx-autoapi
          python -m pip install ghp-import

      - name: Build HTML
        run: |
          cd docs/
          rm -rf _build
          make html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html
