name: Docs

on:
  push:
    branches:
      - main
permissions:
      contents: read
      pages: write
      id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change this to match your preferred Python version
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx_rtd_theme
          sudo apt-get install -y pandoc
      - name: build docs
        run: |
          sphinx-apidoc -o doc refineryframe
          ./tools/update_additional_content.sh
          cd doc
          make html
          cd ..
      - name: Archive documentation
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: doc/_build/html/
  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1


